### ISSUE TITLE
duplicated clocks on other slots you cant delete

### ISSUE THREAD

**Issue by iamh4ppii** [einTosti/BuildSystem#82]
you can produce it if your are hotkeying the clock like nine and hover over 1 
**Screenshots**
![image](https://user-images.githubusercontent.com/96700081/156960815-4765fc10-021b-4d98-82bc-cf0ebb0e2c79.png)

**Server information:**

- Minecraft version: [e.g. 1.18.1]
- Server version [e.g.  Paper]
- Plugin version [e.g. [2.18.1](https://github.com/einTosti/BuildSystem/tree/2.18.1)]

**Comment by einTosti** [comment]
Do you have the setting `Keep Navigator` enabled?

**Comment by iamh4ppii** [comment]
yeah

**Comment by iamh4ppii** [comment]
the best thing if you only keep the navigator on the bind slot ^^

**Comment by einTosti** [comment]
Sadly, this is just limitation of Minecraft itself. When in creative mode, the client does not share any information whatsoever about any click (unlike e.g. survival). 
Therefore, the server does not know if a player in creative is shift-clicking the `X` slot to remove all items or just hot-keying the item to a different slot. And since the idea of the feature is to allow players to use the button to clear their inventory but not the navigator, I will just have to leave everything as it is.
You can still however drop the duplicated Navigators with `Q`
